name: ForSyDe
description: A Methodology for Formal System Design

## uncomment when importing the theme
remote_theme: forsyde/forsyde-web-theme

## paths to exclude from the site generation
exclude: [scripts, Gemfile.lock, Gemfile]

## uncomment the line below when on a project page
plugins:
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-sitemap