name: ForSyDe
description: A Methodology for Formal System Design

remote_theme: forsyde/forsyde-web-theme

exclude: [scripts, Gemfile.lock, Gemfile, README.md]

plugins:
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-sitemap